// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class CentroMedicoDoctor
    {
        public int CentroMedicoDoctorId { get; set; }
        public int DoctorId { get; set; }
        public int CentroMedicoId { get; set; }

        public virtual CentroMedico CentroMedico { get; set; }
        public virtual UsuarioDoctor Doctor { get; set; }
    }
}