// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class CentroMedico
    {
        public CentroMedico()
        {
            CentroMedicoDoctor = new HashSet<CentroMedicoDoctor>();
            CitasAgendadas = new HashSet<CitasAgendadas>();
        }

        public int CentroMedicoId { get; set; }
        public string CentroMedicoNombre { get; set; }
        public string CentroMedicoNumero { get; set; }
        public string CentroMedicoEmail { get; set; }
        public string CentroMedicoLocal { get; set; }

        public virtual ICollection<CentroMedicoDoctor> CentroMedicoDoctor { get; set; }
        public virtual ICollection<CitasAgendadas> CitasAgendadas { get; set; }
    }
}