// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class Dias
    {
        public Dias()
        {
            HorariosDoctor = new HashSet<HorariosDoctor>();
        }

        public int DiaId { get; set; }
        public string NombreDia { get; set; }

        public virtual ICollection<HorariosDoctor> HorariosDoctor { get; set; }
    }
}