// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class Especialidades
    {
        public Especialidades()
        {
            EspecialidadesDoctor = new HashSet<EspecialidadesDoctor>();
        }

        public int EspecialidadId { get; set; }
        public string NombreEspecialidad { get; set; }

        public virtual ICollection<EspecialidadesDoctor> EspecialidadesDoctor { get; set; }
    }
}