// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class EspecialidadesDoctor
    {
        public int EspecialidadesDoctorId { get; set; }
        public int DoctorId { get; set; }
        public int EspecialidadId { get; set; }

        public virtual UsuarioDoctor Doctor { get; set; }
        public virtual Especialidades Especialidad { get; set; }
    }
}