// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class HorariosDoctor
    {
        public int HorarioId { get; set; }
        public int DiaId { get; set; }
        public int DoctorId { get; set; }
        public int CentroMedicoId { get; set; }
        public TimeSpan HoraInicio { get; set; }
        public TimeSpan HoraCierre { get; set; }

        public virtual Dias Dia { get; set; }
        public virtual UsuarioDoctor Doctor { get; set; }
    }
}