// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class InfoCredito
    {
        public InfoCredito()
        {
            UsuarioDoctor = new HashSet<UsuarioDoctor>();
        }



        public int InfoCreditoId { get; set; }
        public string NombreCredito { get; set; }
        public string NumeroTarjetaCredito { get; set; }
        public DateTime? FechaVencimientoCredito { get; set; }
        public string CodigoSeguridadCredito { get; set; }
        public DateTime? FechaIngresoCredito { get; set; }

        public virtual ICollection<UsuarioDoctor> UsuarioDoctor { get; set; }
    }
}