// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class LoginTbl
    {
        public LoginTbl()
        {
            UsuarioDoctor = new HashSet<UsuarioDoctor>();
            UsuarioPaciente = new HashSet<UsuarioPaciente>();
        }

        public int LoginId { get; set; }
        public bool Rol { get; set; }
        public string CorreoElectronico { get; set; }
        public string UsuarioContraseña { get; set; }
        public bool? EstadoLogin { get; set; }

        public virtual ICollection<UsuarioDoctor> UsuarioDoctor { get; set; }
        public virtual ICollection<UsuarioPaciente> UsuarioPaciente { get; set; }
    }
}