// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class UsuarioAsistente
    {
        public int DoctorId { get; set; }
        public string AsistenteContraseña { get; set; }
        public string NombreAsistente { get; set; }
        public bool? EstadoLoginAsist { get; set; }

        public virtual UsuarioDoctor Doctor { get; set; }
    }
}