// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class UsuarioDoctor
    {
        public UsuarioDoctor()
        {
            CentroMedicoDoctor = new HashSet<CentroMedicoDoctor>();
            CitasAgendadas = new HashSet<CitasAgendadas>();
            EspecialidadesDoctor = new HashSet<EspecialidadesDoctor>();
            HorariosDoctor = new HashSet<HorariosDoctor>();
        }

        public int DoctorId { get; set; }
        public byte[] ImagenDoctor { get; set; }
        public int LoginId { get; set; }
        public string NombreDoctor { get; set; }
        public string ApellidoDoctor { get; set; }
        public string TelefonoDoctor { get; set; }
        public string SexoDoctor { get; set; }
        public DateTime? FechaNacimientoDoctor { get; set; }
        public int InfoCreditoId { get; set; }
        public DateTime? FechaCreacionDoctor { get; set; }
        public DateTime? FechaModificacionDoctor { get; set; }
        public int IntervaloCitas { get; set; }

        public virtual InfoCredito InfoCredito { get; set; }
        public virtual LoginTbl Login { get; set; }
        public virtual UsuarioAsistente UsuarioAsistente { get; set; }
        public virtual ICollection<CentroMedicoDoctor> CentroMedicoDoctor { get; set; }
        public virtual ICollection<CitasAgendadas> CitasAgendadas { get; set; }
        public virtual ICollection<EspecialidadesDoctor> EspecialidadesDoctor { get; set; }
        public virtual ICollection<HorariosDoctor> HorariosDoctor { get; set; }
    }
}