// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models
{
    public partial class UsuarioPaciente
    {
        public UsuarioPaciente()
        {
            CitasAgendadas = new HashSet<CitasAgendadas>();
        }

        public int PacienteId { get; set; }
        public byte[] ImagenPaciente { get; set; }
        public int LoginId { get; set; }
        public string NombrePaciente { get; set; }
        public string ApellidoPaciente { get; set; }
        public string TelefonoPaciente { get; set; }
        public string SexoPaciente { get; set; }
        public DateTime FechaNacimientoPaciente { get; set; }
        public DateTime? FechaCreacionPaciente { get; set; }
        public DateTime? FechaModificacionPaciente { get; set; }

        public virtual LoginTbl Login { get; set; }
        public virtual ICollection<CitasAgendadas> CitasAgendadas { get; set; }
    }
}